release-date = "2022-08-12"

[[entries]]
id = "76d24e29-1989-4062-9b82-387fe553e91d"
type = "improvement"
description = "set `_KRAKENW_ENV_TYPE` and `_KRAKENW_ENV_PATH` in environment when dispatching to build environment"
author = "@NiklasRosenstein"
