release-date = "2022-08-12"

[[entries]]
id = "884e2e86-4e3f-4041-913b-f11a2688dfba"
type = "fix"
description = "`VENV` environment type now ensures Pip is up to date in the environment before installing requirements; removed `--use-feature=in-tree-build` flag is it was removed from `20.0.4` to `21.0` and is now the default"
author = "@NiklasRosenstein"

[[entries]]
id = "58a83374-41df-4b1e-aeed-4351e4761bf8"
type = "improvement"
description = "print time it took to install the build environmet"
author = "@NiklasRosenstein"
