release-date = "2022-08-16"

[[entries]]
id = "f21658ab-5a43-4c0a-8030-aa50bc56acae"
type = "improvement"
description = "fall back to writing password into file as plaintext if no keyring backend is available"
author = "@NiklasRosenstein"
