release-date = "2022-12-14"

[[entries]]
id = "7541ba55-6eb7-4082-8637-f78c06c7c898"
type = "fix"
description = "fix `KeyError` that could occurr when creating lockfile if the name of a requirement does not exactly match the distribution name (e.g. due to normalization)"
author = "@NiklasRosenstein"

[[entries]]
id = "0aefcd0b-51a4-4bf4-9ba1-351a51d3aa8a"
type = "feature"
description = "migrate to kraken-common over kraken-core for shared code, support for `kraken.common.buildscript` and BuildDSL build scripts"
author = "@NiklasRosenstein"
