release-date = "2022-12-19"

[[entries]]
id = "30e51d71-f012-47e1-bf8a-8cb9139b06f4"
type = "improvement"
description = "`krakenw` now prints the `kraken` command that it runs inside the build environment"
author = "@NiklasRosenstein"

[[entries]]
id = "16828c43-0035-4732-b7be-70fc4d3e9868"
type = "feature"
description = "`krakenw` now looks for the top-most Kraken build script starting from the current directory and uses that as the Kraken project directory and containing directory for the build directory and build environment."
author = "@NiklasRosenstein"
