[[entries]]
id = "9ab7842b-3b90-44c6-89ba-a59f5db9cca7"
type = "improvement"
description = "use Pip `--use-feature=in-tree-build` flag, this greatly improves the installation time for packages from local requirements"
author = "@NiklasRosenstein"
