name: Python application

on:
  push: { branches: [ develop ], tags: [ "*" ] }
  pull_request: { branches: [ develop ] }

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10", "3.x" ]
    steps:
    - uses: actions/checkout@v2
    - uses: python-slap/slap-cli@gha/install/v1
    - uses: actions/setup-python@v2
      with: { python-version: "${{ matrix.python-version }}" }
    - run: slap install -vv --no-venv-check
    - run: slap test

  rebuild-kraken-base-image:
    runs-on: ubuntu-latest
    needs: [ "test" ]
    # if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_PAT }}
          repository: kraken-build/kraken-base-image
          event-type: kraken-cli release
